/*TMODJS:{"version":18,"md5":"5a98ae6a7fe13e627e7d0bac7188919a"}*/
define(['../../../template',''],function(template){return template('src/artModules/daren/dr_resource_list_data', function($data,$filename
/*``*/) {
'use strict';var $utils=this,$helpers=$utils.$helpers,$escape=$utils.$escape,id=$data.id,nickname=$data.nickname,resourceType=$data.resourceType,resourceTypeStr=$data.resourceTypeStr,price=$data.price,discountPrice=$data.discountPrice,priceRemark=$data.priceRemark,$out='';$out+='<tr id="dren_resource_';
$out+=$escape(id);
$out+='" rid="';
$out+=$escape(id);
$out+='"> <td key="nickname" value="';
$out+=$escape(nickname);
$out+='">';
$out+=$escape(nickname);
$out+='</td> <td key="resourceType" value="';
$out+=$escape(resourceType);
$out+='" id="ipt_resource_type_';
$out+=$escape(id);
$out+='">';
$out+=$escape(resourceTypeStr);
$out+='</td> <!-- <td key="price" value="';
$out+=$escape(price);
$out+='" id="price_';
$out+=$escape(id);
$out+='"> <input type="text" name="price" id="ipt_price_';
$out+=$escape(id);
$out+='" value="';
$out+=$escape(price);
$out+='" class="form-control" onkeyup="value=value.replace(/[^\\d.]/g,\'\')" /> </td> --> <td key="discountPrice" value="';
$out+=$escape(discountPrice);
$out+='" id="discountPrice_';
$out+=$escape(id);
$out+='"> <input type="text" name="price" id="ipt_price_';
$out+=$escape(id);
$out+='" value="';
$out+=$escape(price);
$out+='" style="display:none" class="form-control" onkeyup="value=value.replace(/[^\\d.]/g,\'\')" /> <input type="text" name="discountPrice" id="ipt_discount_price_';
$out+=$escape(id);
$out+='" value="';
$out+=$escape(discountPrice);
$out+='" class="form-control" onkeyup="value=value.replace(/[^\\d.]/g,\'\')" /> </td> <td key="priceRemark" value="';
$out+=$escape(priceRemark);
$out+='" id="priceRemark_';
$out+=$escape(id);
$out+='"> <input class="form-control" type="text" id="ipt_price_remark_';
$out+=$escape(id);
$out+='" name="priceRemark" value="';
$out+=$escape(priceRemark);
$out+='" placeholder="报价备注" /> </td> <td key="op"> <!-- <a href="#" class="bind bind-click permission" code="dr_edit" bind-method="editDrenResource" id="';
$out+=$escape(id);
$out+='" >修改</a> --> <a href="#" class="bind bind-click" bind-method="deleteDrenResource" id="';
$out+=$escape(id);
$out+='" >删除</a> </td> </tr> ';
return new String($out);
});});